### ISSUE TITLE
502: Bad Gateway error

### ISSUE THREAD

**Issue by huemcos** [hassio-addons/addon-traccar#34] opened 2020-01-23 17:43 UTC
This issue started after I upgraded to 0.104
Restarted add-on, HA, Machine still not working.

This is my log:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: Traccar
 Modern GPS Tracking Platform
-----------------------------------------------------------
 Add-on version: 0.6.0
 You are running the latest version of this add-on.
 System: Ubuntu 18.04.2 LTS  (amd64 / qemux86-64)
 Home Assistant version: 0.104.3
 Supervisor version: 195
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] traccar.sh: executing... 
[cont-init.d] traccar.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[09:41:04] INFO: Starting Traccar server...
2020-01-23 09:41:05  INFO: HikariPool-1 - Starting...

**Comment by frenck** [comment] 2020-01-23 18:47
The add-on log looks fine, anything in the HA or Hass.io supervisor logs when starting the add-on and trying to visit the ingress page?

**Comment by huemcos** [comment] 2020-01-23 18:55
This is what I got in HA:
Error doing job: Unclosed connection

**Comment by frenck** [comment] 2020-01-27 10:00
Cannot relate to this issue in any way, sorry m8 :S

**Comment by Z3mpan** [comment] 2020-01-28 11:45
I got the same problem. 

My log says: 

> 20-01-28 11:41:55 ERROR (MainThread) [hassio.api.ingress] Ingress error: Cannot connect to host 172.30.32.1:62572 ssl:None [Connection refused]

**Comment by frenck** [comment] 2020-01-28 11:46
@Z3mpan Please provide the add-on logs as well.

**Comment by Z3mpan** [comment] 2020-01-28 11:50
> Log
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Traccar
 Modern GPS Tracking Platform
-----------------------------------------------------------
 Add-on version: 0.6.1
 You are running the latest version of this add-on.
 System: HassOS 3.8  (armv7 / raspberrypi3)
 Home Assistant version: 0.104.3
 Supervisor version: 195
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] traccar.sh: executing... 
[cont-init.d] traccar.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[12:48:25] INFO: Starting Traccar server...
2020-01-28 12:48:49  INFO: HikariPool-1 - Starting...
2020-01-28 12:48:52  INFO: HikariPool-1 - Start completed.
2020-01-28 12:49:15  INFO: Clearing database change log checksums
2020-01-28 12:49:17  INFO: SELECT COUNT(*) FROM PUBLIC.DATABASECHANGELOGLOCK
2020-01-28 12:49:17  INFO: SELECT COUNT(*) FROM PUBLIC.DATABASECHANGELOGLOCK
2020-01-28 12:49:17  INFO: SELECT LOCKED FROM PUBLIC.DATABASECHANGELOGLOCK WHERE ID=1
2020-01-28 12:49:17  INFO: Waiting for changelog lock....
2020-01-28 12:49:27  INFO: SELECT LOCKED FROM PUBLIC.DATABASECHANGELOGLOCK WHERE ID=1
2020-01-28 12:49:27  INFO: Waiting for changelog lock....
2020-01-28 12:49:37  INFO: SELECT LOCKED FROM PUBLIC.DATABASECHANGELOGLOCK WHERE ID=1
2020-01-28 12:49:37  INFO: Waiting for changelog lock....
2020-01-28 12:49:47  INFO: SELECT LOCKED FROM PUBLIC.DATABASECHANGELOGLOCK WHERE ID=1
2020-01-28 12:49:47  INFO: Waiting for changelog lock....
2020-01-28 12:49:57  INFO: SELECT LOCKED FROM PUBLIC.DATABASECHANGELOGLOCK WHERE ID=1
2020-01-28 12:49:57  INFO: Waiting for changelog lock....
2020-01-28 12:50:07  INFO: SELECT LOCKED FROM PUBLIC.DATABASECHANGELOGLOCK WHERE ID=1
2020-01-28 12:50:07  INFO: Waiting for changelog lock....

**Comment by frenck** [comment] 2020-01-28 11:51
That is not the same issue as posted in here.

**Comment by Z3mpan** [comment] 2020-01-28 11:52
Ahh sorry. 

Thought it was the same. Because I I try to start the add-on I also got 502: Bad gateway

**Comment by huemcos** [comment] 2020-01-28 16:05
After the upgrade to 0.6.1, this is what I'm getting...

[08:04:17] INFO: Starting Traccar server...
2020-01-28 08:04:18 ERROR: Main method error - XML document structures must start and end within the same entity. - SAXParseException (... < Config:37 < Context:269 < Main:110 < ...)
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Configuration file is not a valid XML document
	at org.traccar.Main.run(Main.java:152)
	at org.traccar.Main.main(Main.java:104)
Caused by: java.lang.RuntimeException: Configuration file is not a valid XML document
	at org.traccar.config.Config.<init>(Config.java:52)
	at org.traccar.Context.init(Context.java:269)
	at org.traccar.Main.run(Main.java:110)
	... 1 more
Caused by: java.util.InvalidPropertiesFormatException: org.xml.sax.SAXParseException; lineNumber: 33; columnNumber: 1; XML document structures must start and end within the same entity.
	at sun.util.xml.PlatformXmlPropertiesProvider.load(PlatformXmlPropertiesProvider.java:80)
	at java.util.Properties$XmlSupport.load(Properties.java:1201)
	at java.util.Properties.loadFromXML(Properties.java:881)
	at org.traccar.config.Config.<init>(Config.java:37)
	... 3 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 33; columnNumber: 1; XML document structures must start and end within the same entity.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.endEntity(XMLDocumentFragmentScannerImpl.java:899)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.endEntity(XMLDocumentScannerImpl.java:559)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.endEntity(XMLEntityManager.java:1398)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1916)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.skipChar(XMLEntityScanner.java:1551)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2821)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at sun.util.xml.PlatformXmlPropertiesProvider.getLoadingDoc(PlatformXmlPropertiesProvider.java:106)
	at sun.util.xml.PlatformXmlPropertiesProvider.load(PlatformXmlPropertiesProvider.java:78)
	... 6 more

**Comment by frenck** [comment] 2020-01-28 16:34
Your config file is invalid. Please check the config/traccar.xml file and make sure it is valid XML

**Comment by huemcos** [comment] 2020-01-28 17:38
Oopps.. I was messing with config and erased one line. XML is fixed now. Still getting the bad gateway error though. :-(

**Comment by huemcos** [comment] 2020-01-28 17:50
frenck... here's a new update on this issue. If I'm "not in HA" and I'm in port 8072, it works fine. But when I'm in HA using the addon, I'm getting the bad gateway error. It's strange.

**Comment by frenck** [comment] 2020-02-28 17:14
That is an ingress problem, the add-on is running (as confirmed by you). The rest is out of scope/control of the add-on I'm afraid.

**Closed by frenck** 2020-02-28 17:14 UTC
