### ISSUE TITLE
HTTP 415 Unsupported Media Type - NotSupportedException (...)

### ISSUE THREAD

**Issue by Fabrolly** [hassio-addons/addon-traccar#147] opened 2021-10-27 09:35 UTC
Hi,
I know this report has already been opened but the comments have been blocked and the problem is still there after several months.

It is no longer possible to start this component, I always get:
HTTP 415 Unsupported Media Type - NotSupportedException (...)

Can anyone help?
Thanks

**Comment by frenck** [comment] 2021-11-11 14:30
duplicate of #119

**Closed by frenck** 2021-11-11 14:30 UTC
