### ISSUE TITLE
Error: HTTP 415 Unsupported Media Type - NotSupportedException (...)

### ISSUE THREAD

**Issue by hoanglongutc** [hassio-addons/addon-traccar#119] opened 2021-07-08 07:01 UTC
After upgrading core-2021.7.0, I got an error when accessing traccar:
HTTP 415 Unsupported Media Type - NotSupportedException (...)
I appreciate any help
![traccar_error](https://user-images.githubusercontent.com/35026043/124877089-f1ff8080-dff4-11eb-8c91-0a9f48a6af59.JPG)

**Comment by talexop** [comment] 2021-07-08 07:31
Same for me...

**Comment by fenio** [comment] 2021-07-08 08:35
Same here.

**Comment by ASTPlatinum** [comment] 2021-07-08 18:46
Same

**Comment by lapy** [comment] 2021-07-09 10:35
Same here, it seems there is a problem with the JDBC driver?

**Comment by syzylj** [comment] 2021-07-09 13:24
me too

**Comment by algoodah** [comment] 2021-07-10 07:45
Also having the same problem.

**Comment by pothirak** [comment] 2021-07-11 05:18
I had this problem too when update core to version 2021.7.0.
Core version 2021.7.1 encountered this problem?

**Comment by fenio** [comment] 2021-07-11 05:45
> Core version 2021.7.1 encountered this problem?
Yeah it is the same on .1

**Comment by grbasta** [comment] 2021-07-11 16:48
Same for me...

**Comment by mundeczek** [comment] 2021-07-11 20:50
In core version 2021.7.1 problem still exists

**Comment by hoanglongutc** [comment] 2021-07-12 02:09
Temporary solution. I set up the port for the Web interface and access it directly without the hassio interface

**Comment by grbasta** [comment] 2021-07-12 06:41
> Temporary solution. I set up the port for the Web interface and access it directly without the hassio interface

Hello, explain to me how you would have solved momentarily, do you need to open the router?
Thank you

**Comment by hoanglongutc** [comment] 2021-07-12 07:07
> > Temporary solution. I set up the port for the Web interface and access it directly without the hassio interface
> 
> Hello, explain to me how you would have solved momentarily, do you need to open the router?
> Thank you

Hello, You see the attached file and you need to open the router
![1111111121312321311](https://user-images.githubusercontent.com/35026043/125245197-76fed880-e31a-11eb-8553-146c714ec115.JPG)

**Comment by grbasta** [comment] 2021-07-12 07:18
> > > Temporary solution. I set up the port for the Web interface and access it directly without the hassio interface
> > 
> > 
> > Hello, explain to me how you would have solved momentarily, do you need to open the router?
> > Thank you
> 
> Hello, You see the attached file and you need to open the router
> ![1111111121312321311](https://user-images.githubusercontent.com/35026043/125245197-76fed880-e31a-11eb-8553-146c714ec115.JPG)

Unfortunately it doesn't work for me !! we await the resolution.
thank you 1000

**Comment by hoanglongutc** [comment] 2021-07-12 07:26
> > > > Temporary solution. I set up the port for the Web interface and access it directly without the hassio interface
> > > 
> > > 
> > > Hello, explain to me how you would have solved momentarily, do you need to open the router?
> > > Thank you
> > 
> > 
> > Hello, You see the attached file and you need to open the router
> > ![1111111121312321311](https://user-images.githubusercontent.com/35026043/125245197-76fed880-e31a-11eb-8553-146c714ec115.JPG)
> 
> Unfortunately it doesn't work for me !! we await the resolution.
> thank you 1000

You can try another port e.g. 8093
Try accessing in the local network before configuring on the router

**Comment by shirou93** [comment] 2021-07-12 15:21
Same issue

**Comment by fenio** [comment] 2021-07-13 14:55
Core version 2021.7.2 also doesn't fix that issue.

**Comment by justinmbrock** [comment] 2021-07-14 07:23
I thought I was doing something wrong setting this up for the first time. I can open a port and log in to the web interface to verify my devices are being tracked, but data still isn't being sent to Home Assistant. Is that also because of this error, or does this addon not send anything back to use on a dashboard?

**Comment by desosav** [comment] 2021-07-14 07:58
Same here :(

**Comment by HagenGro** [comment] 2021-07-14 20:57
Hi, I found this lines in my logfile after the core-2021.6.6 Update to core-2021.7.2:
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
2021-07-14 22:46:53  INFO: HikariPool-1 - Starting...
2021-07-14 22:46:54  WARN: Registered driver with driverClassName=com.mysql.jdbc.Driver was not found, trying direct instantiation.

**Comment by justinmbrock** [comment] 2021-07-15 02:50
I created https://github.com/hassio-addons/addon-traccar/pull/122 which replaces `com.mysql.jdbc.Driver` with `com.mysql.cj.jdbc.Driver`.

**Comment by justinmbrock** [comment] 2021-07-15 03:00
And a quick search shows this is the only place in the hassio-addons or home-assistant orgs with `com.mysql.jdbc.Driver` anywhere in the code.

**Comment by grbasta** [comment] 2021-07-15 16:14
> And a quick search shows this is the only place in the hassio-addons or home-assistant orgs with `com.mysql.jdbc.Driver` anywhere in the code.

Solutions?

**Comment by wishx** [comment] 2021-07-15 21:20
> And a quick search shows this is the only place in the hassio-addons or home-assistant orgs with `com.mysql.jdbc.Driver` anywhere in the code.

It's awaiting review.

**Comment by sinclairpaul** [comment] 2021-07-16 00:20
The PR referenced won't fix the issue (it will however clear an error mentioning a deprecated class), from what I can see it likely is an issue with the ingress functionality in HA itself.  If you want a workaround, as suggested previously, configure a port in the addon:

![image](https://user-images.githubusercontent.com/24625998/125873511-365aa5d7-55a0-49f4-8b4b-e225dfdd6dc0.png)


And access directly.

**Comment by ioannispelelis** [comment] 2021-07-16 09:15
Same issue as well.
The workaround works thanks, but only internally except if i redirect the port added to the addon from my router to HA.
Which would be exposing the traccar addon diretly on the web... which i dont want to
So for the moment i will only access it internally http://192.168.x.x:yyyy > it obviously gives a cert error but what can you do..
Until it is fixed at least i have acces to it somehow

**Comment by hoanglongutc** [comment] 2021-07-16 11:56
Now there is a new version: core-2021.7.3
Is the issue still resolved in this version?

**Comment by shirou93** [comment] 2021-07-16 12:07
@hoanglongutc nope. This is addon issue not HA. Addon have error in ingress after update.

**Comment by hoanglongutc** [comment] 2021-07-19 08:00
Currently the problem is not resolved.
I have downgraded to core-2021.6.6 version to have a card to use while waiting for a new update of Traccar

**Comment by justinmbrock** [comment] 2021-07-19 20:48
Is there a way to downgrade the core version without a snapshot?

**Comment by bakerkj** [comment] 2021-07-20 01:03
This is an issue for me as well.

**Comment by pruwait** [comment] 2021-07-26 17:23
core-2021.7.4 problem not resolved

**Comment by fenio** [comment] 2021-07-27 04:54
@frenck Any comments on that?
Are you aware of the issue? Are there plans to fix it?

**Comment by Zagor4** [comment] 2021-07-28 19:44
Same error here ! Thanks

**Comment by asiersan** [comment] 2021-07-28 21:36
same here!

**Comment by Gummientchen** [comment] 2021-07-29 16:11
same problem here.

**Comment by stanleygreenwood** [comment] 2021-08-03 13:00
same here

**Comment by jkmf** [comment] 2021-08-05 10:17
core-2021.8.1, it still doesn't work

**Comment by fenio** [comment] 2021-08-05 16:40
Guys it will be broken on any HA version starting from 2021.7.
That component needs to be fixed not HA.

**Comment by lapy** [comment] 2021-08-05 17:16
Guys I am trying to fix it, and I got one step further.

The endpoint that is failing is **/server**
Adding `proxy_set_header Content-Type application/json;` in **/etc/nginx/includes/proxy_params.conf** then executing _nginx -s reload_ this endpoint is not failing anymore in ingress and I see the login screen. But then the **/session** endpoint is failing with the same error.

**Comment by lapy** [comment] 2021-08-05 17:19
It looks like HA changed the way the ingress requests headers are formed, need to investigate what changed

**Comment by hoanglongutc** [comment] 2021-08-09 04:19
More than a month has passed since I created the request. It seems that this addon is no longer supported.
Hope someone can help with this. I'm not a coding expert, so it's very difficult to find a way to fix it

**Comment by grizzlylife** [comment] 2021-08-10 09:47
Also doesn't work for me. Since it does not work, can anyone use an alternative to this application? As a specialist, I know that the best monitoring application on the market is Wialon from Gurtam, but it is paid.

**Comment by desosav** [comment] 2021-08-10 14:43
> Also doesn't work for me. Since it does not work, can anyone use an alternative to this application? As a specialist, I know that the best monitoring application is Wialon from Gurtam, but it is paid.

Check the previous comments to find a way to make it work using a port of your preference. Make sure you open that port on your firewall as well if you want to enable external access.

**Comment by shirou93** [comment] 2021-08-11 21:24
New update 0.13.1 have also same issue.

**Comment by frenck** [comment] 2021-08-11 21:35
> New update 0.13.1 have also same issue.

The issue is also still open and the release notes of that version do not specify anything about this problem. So yeah... still the same issue.

The last update was to roll out a CI change and basic dependency updates. Regular maintenance.

**Closed** 2021-11-11 15:08 UTC
